services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: dev
    ports:
    - "8000:8000"
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: dev
    ports:
    - "8001:8001"
